load = (new_data) =>
    data.elts = []
    data.lnks = []

    new_data = JSON.parse(new_data)
    for elt in new_data.elts
        data.elts.push(new E[elt.name](elt.x, elt.y, elt.text, elt.fixed))
    for lnk in new_data.lnks
        data.lnks.push(new @[lnk.name](data.elts[lnk.source], data.elts[lnk.target]))

    state.selection = []

save = =>
    localStorage.setItem('data', objectify())


generate_url = ->
    if state.no_save
        state.no_save = false
        return
    hash = '#' + btoa(objectify())
    if location.hash != hash
        history.pushState(null, null, hash)


if not localStorage.getItem('data')
    localStorage.setItem('data', atob('eyJlbHRzIjpbeyJuYW1lIjoiUHJvY2VzcyIsIngiOjIwMCwieSI6NzUsInRleHQiOiJTdGFydCIsImZpeGVkIjp0cnVlfSx7Im5hbWUiOiJEZWNpc2lvbiIsIngiOjIwMCwieSI6MjAwLCJ0ZXh0IjoiRG8geW91XG51bmRlcnN0YW5kXG5mbG93IGNoYXJ0cz8iLCJmaXhlZCI6dHJ1ZX0seyJuYW1lIjoiUHJvY2VzcyIsIngiOjU3NSwieSI6MjAwLCJ0ZXh0IjoiR29vZCIsImZpeGVkIjp0cnVlfSx7Im5hbWUiOiJQcm9jZXNzIiwieCI6ODI1LCJ5IjozMDAsInRleHQiOiJMZXQncyBnb1xuIGRyaW5rLiIsImZpeGVkIjp0cnVlfSx7Im5hbWUiOiJQcm9jZXNzIiwieCI6MTAwMCwieSI6MzAwLCJ0ZXh0IjoiSGV5LCBJIHNob3VsZFxudHJ5IGluc3RhbGxpbmdcbkZyZWVCU0QhIiwiZml4ZWQiOnRydWV9LHsibmFtZSI6IkRlY2lzaW9uIiwieCI6MjAwLCJ5Ijo0MDAsInRleHQiOiJPa2F5LlxuWW91IHNlZSB0aGVcbmxpbmUgbGFiZWxlZFxuXCJ5ZXNcIj8iLCJmaXhlZCI6dHJ1ZX0seyJuYW1lIjoiRGVjaXNpb24iLCJ4IjoyMDAsInkiOjYwMCwidGV4dCI6IkJ1dCB5b3VcbnNlZSB0aGUgb25lc1xubGFiZWxlZCBcIm5vXCIuIiwiZml4ZWQiOnRydWV9LHsibmFtZSI6IlByb2Nlc3MiLCJ4IjoyMDAsInkiOjcyNSwidGV4dCI6Ikxpc3Rlbi4iLCJmaXhlZCI6dHJ1ZX0seyJuYW1lIjoiUHJvY2VzcyIsIngiOjM1MCwieSI6NzI1LCJ0ZXh0IjoiSSBoYXRlXG55b3UuIiwiZml4ZWQiOnRydWV9LHsibmFtZSI6IlByb2Nlc3MiLCJ4Ijo0MDAsInkiOjYwMCwidGV4dCI6IldhaXQsXG53aGF0PyIsImZpeGVkIjp0cnVlfSx7Im5hbWUiOiJEZWNpc2lvbiIsIngiOjU3NSwieSI6NDAwLCJ0ZXh0IjoiLi4uYW5kIHlvdSBjYW5cbnNlZSB0aGUgb25lc1xubGFiZWxlZCBcIm5vXCI/IiwiZml4ZWQiOnRydWV9LHsibmFtZSI6IkRlY2lzaW9uIiwieCI6NTc1LCJ5Ijo1NzUsInRleHQiOiJCdXQgeW91XG5qdXN0IGZvbGxvd2VkXG50aGVtIHR3aWNlISIsImZpeGVkIjp0cnVlfSx7Im5hbWUiOiJQcm9jZXNzIiwieCI6ODI1LCJ5Ijo1NzUsInRleHQiOiIoVGhhdCB3YXNuJ3QgYSBxdWVzdGlvbi4pIiwiZml4ZWQiOnRydWV9LHsibmFtZSI6IlByb2Nlc3MiLCJ4Ijo4MjUsInkiOjQyNSwidGV4dCI6IlNjcmV3IGl0LiIsImZpeGVkIjp0cnVlfV0sImxua3MiOlt7Im5hbWUiOiJMaW5rIiwic291cmNlIjowLCJ0YXJnZXQiOjF9LHsibmFtZSI6IkxpbmsiLCJzb3VyY2UiOjEsInRhcmdldCI6Mn0seyJuYW1lIjoiTGluayIsInNvdXJjZSI6MiwidGFyZ2V0IjozfSx7Im5hbWUiOiJMaW5rIiwic291cmNlIjozLCJ0YXJnZXQiOjR9LHsibmFtZSI6IkxpbmsiLCJzb3VyY2UiOjEsInRhcmdldCI6NX0seyJuYW1lIjoiTGluayIsInNvdXJjZSI6NSwidGFyZ2V0Ijo2fSx7Im5hbWUiOiJMaW5rIiwic291cmNlIjo2LCJ0YXJnZXQiOjd9LHsibmFtZSI6IkxpbmsiLCJzb3VyY2UiOjcsInRhcmdldCI6OH0seyJuYW1lIjoiTGluayIsInNvdXJjZSI6NiwidGFyZ2V0Ijo5fSx7Im5hbWUiOiJMaW5rIiwic291cmNlIjo1LCJ0YXJnZXQiOjEwfSx7Im5hbWUiOiJMaW5rIiwic291cmNlIjoxMCwidGFyZ2V0IjoxMX0seyJuYW1lIjoiTGluayIsInNvdXJjZSI6MTEsInRhcmdldCI6MTJ9LHsibmFtZSI6IkxpbmsiLCJzb3VyY2UiOjEyLCJ0YXJnZXQiOjEzfSx7Im5hbWUiOiJMaW5rIiwic291cmNlIjoxMywidGFyZ2V0IjozfSx7Im5hbWUiOiJMaW5rIiwic291cmNlIjoxMCwidGFyZ2V0IjoyfV19'))
